### ISSUE TITLE
Create a Gemfile to handle dependencies

### ISSUE THREAD

**Issue by nixpulvis** [alexjohnson505/quadcopter_docs#1]
[Bundler](http://bundler.io) is the way to go to handle dependencies in ruby. So that you can install and maintain versions of external libraries with a simple `bundle install`

**Comment by alexjohnson505** [comment]
Good call.
Fixed with https://github.com/alexjohnson505/quadrocopter_docs/commit/43822332f7c95eb900a7e95ad5236276a2459255
