### ISSUE TITLE
Navigation Error causes innapropriate 404s

### ISSUE THREAD

**Issue by alexjohnson505** [alexjohnson505/quadcopter_docs#10]
Navigating to a page or directory that you are already on sometimes results in a 404 error.

**Comment by nixpulvis** [comment]
This seems really weird. Any more information on when this happens?

**Comment by alexjohnson505** [comment]
Issue resolved with https://github.com/alexjohnson505/quadrocopter_docs/commit/deceace546839c9f5a561a919b3589a85cec0026

I was using relative links (example `href="docs/hardware"`) instead of absolute (`"/docs/hardware"`).
